#!/bin/sh

# Convenience script for running SWIG before it is installed.
# Intended for ad-hoc usage and not by the test-suite or examples.

builddir=`dirname "$0"`
SWIG_LIB='/home/harrington/scale_iot_design_04-30-2025/swig-4.3.1/Lib'
export SWIG_LIB
exec "$builddir/swig" "$@"
