
#include <stddef.h>
// server_cert.h
#pragma once

// File: main/server_cert.h
// Generated by embedding your PEM blobs (using 
// `xxd -i fullchain.pem > server_cert.c`, etc.)

extern const unsigned char server_cert_pem_start[] asm("_binary_fullchain_pem_start");
extern const unsigned char server_cert_pem_end[]   asm("_binary_fullchain_pem_end");
extern const unsigned char server_key_pem_start[]  asm("_binary_privkey_pem_start");
extern const unsigned char server_key_pem_end[]    asm("_binary_privkey_pem_end");

#ifdef __cplusplus
extern "C" {
#endif

void server_cert_init(void);

#ifdef __cplusplus
}
#endif